apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: 付与したいロール
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:masters

