apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: 付与したいロール
      username: system:node:ip-192-168-1-160.ec2.internal
      groups:
        - system:masters

